Jobs-To-Check: # Use all CAPS
- "BREWER"
- "CHEF"
- "DOCTOR"
- "FARMER"
- "HUNTER"
- "LANDSCAPER"
- "LUMBERJACK"
- "ENGINEER"
- "TOURGUIDE"
- "CITYADVISOR"
- "COMMUNITYCOORDINATOR"
- "CONSTRUCTOR"
- "DOCINTERN"
- "ECONOMYSECRETARY"
- "ENVIRONMENTMANAGER"
- "HOSPITALSECRETARY"
- "JUDGE"
- "POLICE"
- "PROPERTYINSPECTOR"
- "RANGER"
- "SENIORCOMMUNITYCOORDINATOR"
- "SENIORECONOMYSECRETARY"
- "SENIORENVIRONMENTMANAGER"
- "SENIORRANGER"
- "SENIORTOURGUIDE"
- "SERGEANT"